### ISSUE TITLE
Submit to OPA ecosystem page

### ISSUE THREAD

**Issue by anderseknert** [EliuX/flask-opa#12]
Hi @EliuX ! 

And thanks for a nice little library 👍 I'm cleaning up the front page README of the contrib repo and am about to move all the links pointing to external projects like this one to the [OPA ecosystem](https://www.openpolicyagent.org/docs/latest/ecosystem/) page. Was wondering if you would like to submit your project to that? Instructions for doing so can be found [here](https://github.com/open-policy-agent/opa/tree/master/docs#integration-index).

Btw, I've linked to your project from my personal list of [favorite OPA projects](https://github.com/anderseknert/awesome-opa) :)

(one last thing, the Flask link first thing in your README seems broken).

**Comment by EliuX** [comment]
Thanks @anderseknert, sorry for the late response. I will make that correction that you pointed out. Yes, I would like to submit the project for that for sure.
